Algoritmo "teste_mesa"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/11/2021
Var
// Seção de Declarações das variáveis 
   x,y:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   x<-0
   y<-4
   enquanto x<3 faca
   y<-y+2
   x<-x+1
   escreval(x," - ",y)
   fimenquanto
   
   

Fimalgoritmo