Algoritmo "glicose"

Var
// Seção de Declarações das variáveis 

   glicose:real
   class:caracter

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite a medida da glicose: ")
   leia(glicose)

     se (glicose <=100) entao
      escreva("NORMAL")
     senao
      se (glicose<=140)entao
       escreva("ELEVADA")
      senao
       se (glicos >140)entao
          escreva("DIABETES")
       fimse


Fimalgoritmo
